# These are supported funding model platforms

github: [kyranet]
patreon: quantumlytangled
open_collective: # Replace with a single Open Collective username
ko_fi: quantumlytangled
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://donate.skyra.pw/paypal
