version: '2.4'

services:
  outflux:
    image: skyrabot/outflux:latest
    container_name: outflux
    restart: unless-stopped
    tty: true
    build: ./
    environment:
      INFLUX_BASE_URL: 'http://host.docker.internal:8285'
    ports:
      - '8286:8286'
